### ISSUE TITLE
Headings mixin loop doesn't limit compiled selectors to parameters

### ISSUE THREAD

**Issue by jwandrews** [carpages/gemini-css#4]
### Source
```scss
$base: (
  spacing: 16px
);

@mixin headings($from: 1, $to: 6) {
  %base-heading {
    @content;
  }
  
  @if $from >= 1 and $to <= 6 {
    @for $i from $from through $to {
      h#{$i} {
        @extend %base-heading;
      }
    }
  }
}

@include headings(1, 3) {
  margin-bottom: map-get($base, spacing) / 2;
}

@include headings(4, 6) {
  margin-bottom: map-get($base, spacing) / 4;
}
```

### Expected Output
```css
h1, h2, h3 {
  margin-bottom: 8px;
}

h4, h5, h6 {
  margin-bottom: 4px;
}
```

### Actual Output
```css
h1, h2, h3, h4, h5, h6 {
  margin-bottom: 8px;
}

h1, h2, h3, h4, h5, h6 {
  margin-bottom: 4px;
}
```

#### References
* Sassmeister example: [Link](http://www.sassmeister.com/gist/5633b2047ab68e6c3e968904d50e3a35)
* Sass Issue: https://github.com/sass/sass/issues/2220
